### ISSUE TITLE
Bioconductor carpentries instructors

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/bioconductor-training#22]
Are you a carpentries instructor, are part of the Bioconductor community, and would like to be listed in the forthcoming list? Please provide you name, location, institution and www page to this issue either to this issue, or add yourself directly to [bioc-instructors.md](https://github.com/Bioconductor/bioconductor-teaching/blob/master/bioc-instructors.md) with a PR.

**Comment by mblue9** [comment]
What do you think about also adding affiliation to make it easier to see where they're working? e.g. people at same institute may be able to more easily co-organise workshops together.

**Comment by lgatto** [comment]
Or a link to a web page to get all the relevant info?

**Comment by mblue9** [comment]
Both? As having the affiliation in the md file here would be good for easily seeing (and using if we include it in the map with interactive hover) and then could click the web page link for more info.

**Comment by lgatto** [comment]
Sure. I just want to minimise maintenance.

**Comment by lgatto** [comment]
I'll update the instructors file.

**Comment by SaskiaFreytag** [comment]
Name: Saskia Freytag
Location: Melbourne, Australia

**Comment by mblue9** [comment]
Initial draft of a webpage https://mblue9.github.io/bioconductor-carpentries/instructors.html

**Comment by omsai** [comment]
Name: Pariksheet Nanda
Location: Ann Arbor, Michigan

**Comment by LiNk-NY** [comment]
Name: Marcel Ramos
Location: New York, USA

**Comment by liz-is** [comment]
Name: Liz Ing-Simmons
Location: London, UK
Institution: MRC London Institute of Medical Sciences
https://liz.rbind.io/

**Comment by Kayla-Morrell** [comment]
Name: Kayla Interdonato
Location: Buffalo, NY
Institution: Roswell Park Comprehensive Cancer Center

**Comment by mdozmorov** [comment]
Name: Mikhail Dozmorov
Location: Richmond, VA
Institution: Virginia Commonwealth University

**Comment by spholmes** [comment]
Name: Susan Holmes
Location: Stanford, California and Portugal
Institution: Stanford University
https://susan.su.domains/

**Comment by Osano1900** [comment]
Name: Maureen Osano
Location: Kenya, Africa
Institution: Kenya Medical Research Institute (KEMRI)

**Comment by javibio-git** [comment]
Name: Javier Carpinteyro-Ponce
Location: Maryland, USA
Institution: Carnegie Institution for Science
https://bse.carnegiescience.edu/javier-carpinteyro-ponce

**Comment by mblue9** [comment]
Hi all, the list of Bioconductor Carpentries instructors is now available at https://training.bioconductor.org/carpentries/instructors.html. If you'd like to add yourself or update your details, please submit a pull request to update the instructors TSV as mentioned on that page. The `bioc-instructors.md` file is no longer used, and the process has moved to a more streamlined approach.
